replicaCount: 1
prometheus:
  name: prometheus
  group: metrics
  container:
    image: prom/prometheus
    port: 9090
  cservice:
    type: ClusterIP
    port: 9090
  nservice:
    name: prometheusnp
    type: NodePort
    nodePort: 30909
  volume:
    name: prometheus-config
    volumeMounts:
      mountPath: /etc/prometheus/prometheus.yml
      subPath: prometheus.yml
      readOnly: true
  